unique_ids:
  assets:
    standard-page.html: NVS7SQ5DUJ5QM3TEIB435SYEAANOA4RH
    theme.css: SEM3MWWWM63HFIVTDGIUXWILO3VZDTRQ
  forms:
    Form1: W4URRGU3DWSRBLR5EKGZAKZJUUZU4YMG
  modules: {}
  scripts: {}
  server_modules: {}
